import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.scss";
import Layout from "@/components/layout/layout";
import Home from "@/components/home/home";

const inter = Inter({ subsets: ["latin"] });

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
       
          <Home/>
      
      </Layout>
    </>
  );
}
